### ISSUE TITLE
[Help]: discoverServices() method is not working after disconnect and connect back again

### ISSUE THREAD

**Issue by vontdeux** [chipweinberger/flutter_blue_plus#1053]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.33.5

### Flutter Version

3.16.0

### What OS?

Android

### OS Version

10

### Bluetooth Module

HC-05

### What is your problem?

Connect to a device, discover services, subscribe to it's characteristic - works fine
disconnect , connect back again, try discover device, it will time out 15s
what i did is i just add a disconnect button and method
```
ScanResultTile(
            result: r,
            onTap: () => onConnectPressed(r.device),
            onDis: () => onDisconnectPressed(r.device),
          ),
```

and 
```
return ExpansionTile(
      title: _buildTitle(context),
      leading: Text(widget.result.rssi.toString()),
      trailing: Container(
        child: isConnected ? _buildDisconnectButton(context) : _buildConnectButton(context),
      ),
```

tested on this modified example app and my app, both having same results

### Logs

```shell
Restarted application in 2,514ms.
I/flutter (14514): [FBP] <setLogLevel> args: 5
D/[FBP-Android](14514): [FBP] onMethodCall: setLogLevel
I/flutter (14514): [FBP] <setLogLevel> result: true
D/[FBP-Android](14514): [FBP] onMethodCall: flutterRestart
D/[FBP-Android](14514): [FBP] disconnectAllDevices(flutterRestart)
D/[FBP-Android](14514): [FBP] calling disconnect: C0:20:12:14:10:01
D/BluetoothGatt(14514): cancelOpen() - device: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] calling close: C0:20:12:14:10:01
D/BluetoothGatt(14514): close()
D/BluetoothGatt(14514): unregisterApp() - mClientIf=31
D/[FBP-Android](14514): [FBP] connectedPeripherals: 0
I/flutter (14514): [FBP] <getAdapterState> args: null
D/[FBP-Android](14514): [FBP] onMethodCall: getAdapterState
I/flutter (14514): [FBP] <getAdapterState> result: {adapter_state: 4}
I/TRuntime.CctTransportBackend(14514): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/flutter (14514): [FBP] <startScan> args: {with_services: [], with_remote_ids: [], with_names: [], with_keywords: [], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_legacy: false, android_scan_mode: 2, android_uses_fine_location: false}
D/[FBP-Android](14514): [FBP] onMethodCall: startScan
D/BluetoothAdapter(14514): isLeEnabled(): ON
D/BluetoothLeScanner(14514): onScannerRegistered() - status=0 scannerId=31 mScannerId=0
I/flutter (14514): [FBP] <startScan> result: true
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -57, connectable: 1, manufacturer_data: {}, remote_id: C4:22:10:17:0C:87, platform_name: B_TBCD001Z0004 , service_data: {}, adv_name: B_TBCD001Z0004
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -85, manufacturer_data: {76: 12020002}, remote_id: D4:74:63:66:9D:12, service_data: {}}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -77, connectable: 1, manufacturer_data: {76: 1005101c9848ce}, remote_id: 76:3A:44:A3:3D:C2, tx_power_level: 17, service_data: {}}]}
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -57, connectable: 1, manufacturer_data: {17224: c02012141001}, remote_id: C0:20:12:14:10:01, platform_name: B_vont9675, service_data: {}, adv_name: B_vont9675, service_uuids: [fff0]}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -59, manufacturer_data: {}, remote_id: 3D:FA:52:92:43:CD, service_data: {fef3: 4a1723533558351132dd8103adc06c43bc06b358c1471dc75f6e6b}}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -46, connectable: 1, manufacturer_data: {}, remote_id: D4:32:0E:33:0D:1B, platform_name: STRATOS 2_0D1B, service_data: {fe78: d4320e330d1b5e4e010104a00000}, adv_name: STRATOS 2_0D1B, service_uuids: [fef5, fee7]}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -33, connectable: 1, manufacturer_data: {76: 1005191c81e4a7}, remote_id: 6D:40:76:E0:25:17, tx_power_level: 12, service_data: {}}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -38, manufacturer_data: {6: 010920224d7a06f09c05f69343de24de1c37854326f800f71cdb7f}, remote_id: 13:D6:57:43:13:66, service_data: {}}]}
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -33, manufacturer_data: {76: 12020000}, remote_id: E7:D2:17:A5:69:C0, service_data: {}}]}
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -93, manufacturer_data: {76: 12020003}, remote_id: D1:9F:AA:F4:D3:AA, service_data: {}}]}
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -91, manufacturer_data: {6: 01092002a7d758d80e065bf7924466327f257b13f60dbce876866a}, remote_id: 00:EB:10:CF:A2:4D, service_data: {}}]}
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] <connect> args: {remote_id: C0:20:12:14:10:01, auto_connect: 0}
D/[FBP-Android](14514): [FBP] onMethodCall: connect
D/BluetoothGatt(14514): connect() - device: C0:20:12:14:10:01, auto: false
D/BluetoothGatt(14514): registerApp()
D/BluetoothGatt(14514): registerApp() - UUID=a92b2497-477d-4899-8345-831658df32cc
D/BluetoothGatt(14514): onClientRegistered() - status=0 clientIf=32
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/BluetoothGatt(14514): onClientConnectionState() - status=0 clientIf=32 device=C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onConnectionStateChange:connected
D/[FBP-Android](14514): [FBP]   status: SUCCESS
I/flutter (14514): [FBP] <connect> result: true
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:20:12:14:10:01, connection_state: 1}
I/flutter (14514): [FBP] <readRssi> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: readRssi
D/BluetoothGatt(14514): readRssi() - device: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onReadRemoteRssi:
D/[FBP-Android](14514): [FBP]   rssi: -56
D/[FBP-Android](14514): [FBP]   status: GATT_SUCCESS (0)
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] <readRssi> result: true
I/flutter (14514): [FBP] [[ OnReadRssi ]] result: {error_string: GATT_SUCCESS, rssi: -56, success: 1, remote_id: C0:20:12:14:10:01, error_code: 0}
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=16 latency=0 timeout=2000 status=0
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=16 latency=0 timeout=2000 status=0
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] <discoverServices> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onMethodCall: discoverServices
D/BluetoothGatt(14514): discoverServices() - device: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onScanResult
D/BluetoothGatt(14514): onSearchComplete() = Device=C0:20:12:14:10:01 Status=0
D/[FBP-Android](14514): [FBP] onServicesDiscovered:
D/[FBP-Android](14514): [FBP]   count: 2
D/[FBP-Android](14514): [FBP]   status: 0GATT_SUCCESS
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] <discoverServices> result: true
I/flutter (14514): [FBP] [[ OnDiscoveredServices ]] result: {error_string: GATT_SUCCESS, success: 1, remote_id: C0:20:12:14:10:01, error_code: 0, services: [{included_services: [], characteristics: [{descriptors: [{service_uuid: ffe0, remote_id: C0:20:12:14:10:01, descriptor_uuid: 2902, characteristic_uuid: ffe1}], service_uuid: ffe0, remote_id: C0:20:12:14:10:01, characteristic_uuid: ffe1, properties: {broadcast: 0, write_without_response: 1, notify_encryption_required: 0, read: 1, authenticated_signed_writes: 0, extended_properties: 0, indicate: 0, indicate_encryption_required: 0, write: 1, notify: 1}}], service_uuid: ffe0, is_primary: 1, remote_id: C0:20:12:14:10:01}, {included_services: [], characteristics: [{descriptors: [], service_uuid: ff00, remote_id: C0:20:12:14:10:01, characteristic_uuid: ff02, properties: {broadcast: 0, write_without_response: 1, notify_encryption_required: 0, read: 0, authenticated_signed_writes: 0, extended_properties: 0, indicate: 0, indicate_encryption_required: 0, write: 1, n
D/[FBP-Android](14514): [FBP] onScanResult
D/[FBP-Android](14514): [FBP] onScanResult
I/flutter (14514): [FBP] <stopScan> args: null
D/[FBP-Android](14514): [FBP] onMethodCall: stopScan
D/BluetoothAdapter(14514): isLeEnabled(): ON
I/flutter (14514): [FBP] <stopScan> result: true
I/flutter (14514): [FBP] <disconnect> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: disconnect
D/BluetoothGatt(14514): cancelOpen() - device: C0:20:12:14:10:01
D/BluetoothGatt(14514): onClientConnectionState() - status=0 clientIf=32 device=C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onConnectionStateChange:disconnected
D/[FBP-Android](14514): [FBP]   status: SUCCESS
D/BluetoothGatt(14514): close()
D/BluetoothGatt(14514): unregisterApp() - mClientIf=32
I/flutter (14514): [FBP] <disconnect> result: true
I/flutter (14514): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:20:12:14:10:01, connection_state: 0}
I/flutter (14514): [FBP] <readRssi> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: readRssi
I/flutter (14514): [FBP] <connect> args: {remote_id: C0:20:12:14:10:01, auto_connect: 0}
D/[FBP-Android](14514): [FBP] onMethodCall: connect
D/BluetoothGatt(14514): connect() - device: C0:20:12:14:10:01, auto: false
D/BluetoothGatt(14514): registerApp()
D/BluetoothGatt(14514): registerApp() - UUID=3750b8a1-b58c-45b4-b749-de869759b71e
D/BluetoothGatt(14514): onClientRegistered() - status=0 clientIf=31
I/flutter (14514): [FBP] <connect> result: true
D/BluetoothGatt(14514): onClientConnectionState() - status=0 clientIf=31 device=C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onConnectionStateChange:connected
D/[FBP-Android](14514): [FBP]   status: SUCCESS
I/flutter (14514): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:20:12:14:10:01, connection_state: 1}
I/flutter (14514): [FBP] <readRssi> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: readRssi
D/BluetoothGatt(14514): readRssi() - device: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onReadRemoteRssi:
D/[FBP-Android](14514): [FBP]   rssi: -56
D/[FBP-Android](14514): [FBP]   status: GATT_SUCCESS (0)
I/flutter (14514): [FBP] <readRssi> result: true
I/flutter (14514): [FBP] [[ OnReadRssi ]] result: {error_string: GATT_SUCCESS, rssi: -56, success: 1, remote_id: C0:20:12:14:10:01, error_code: 0}
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=16 latency=0 timeout=2000 status=0
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(14514): onConnectionUpdated() - Device=C0:20:12:14:10:01 interval=16 latency=0 timeout=2000 status=0
I/flutter (14514): [FBP] <discoverServices> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: discoverServices
D/BluetoothGatt(14514): discoverServices() - device: C0:20:12:14:10:01
I/flutter (14514): [FBP] <discoverServices> result: true
D/BluetoothGatt(14514): onSearchComplete() = Device=C0:20:12:14:10:01 Status=0
D/[FBP-Android](14514): [FBP] onServicesDiscovered:
D/[FBP-Android](14514): [FBP]   count: 2
D/[FBP-Android](14514): [FBP]   status: 0GATT_SUCCESS
I/flutter (14514): [FBP] [[ OnDiscoveredServices ]] result: {error_string: GATT_SUCCESS, success: 1, remote_id: C0:20:12:14:10:01, error_code: 0, services: [{included_services: [], characteristics: [{descriptors: [{service_uuid: ffe0, remote_id: C0:20:12:14:10:01, descriptor_uuid: 2902, characteristic_uuid: ffe1}], service_uuid: ffe0, remote_id: C0:20:12:14:10:01, characteristic_uuid: ffe1, properties: {broadcast: 0, write_without_response: 1, notify_encryption_required: 0, read: 1, authenticated_signed_writes: 0, extended_properties: 0, indicate: 0, indicate_encryption_required: 0, write: 1, notify: 1}}], service_uuid: ffe0, is_primary: 1, remote_id: C0:20:12:14:10:01}, {included_services: [], characteristics: [{descriptors: [], service_uuid: ff00, remote_id: C0:20:12:14:10:01, characteristic_uuid: ff02, properties: {broadcast: 0, write_without_response: 1, notify_encryption_required: 0, read: 0, authenticated_signed_writes: 0, extended_properties: 0, indicate: 0, indicate_encryption_required: 0, write: 1, n
I/flutter (14514): [FBP] <disconnect> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: disconnect
D/BluetoothGatt(14514): cancelOpen() - device: C0:20:12:14:10:01
D/BluetoothGatt(14514): onClientConnectionState() - status=0 clientIf=31 device=C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onConnectionStateChange:disconnected
D/[FBP-Android](14514): [FBP]   status: SUCCESS
D/BluetoothGatt(14514): close()
D/BluetoothGatt(14514): unregisterApp() - mClientIf=31
I/flutter (14514): [FBP] <disconnect> result: true
I/flutter (14514): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:20:12:14:10:01, connection_state: 0}
I/flutter (14514): [FBP] <readRssi> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: readRssi
I/flutter (14514): [FBP] <connect> args: {remote_id: C0:20:12:14:10:01, auto_connect: 0}
D/[FBP-Android](14514): [FBP] onMethodCall: connect
D/BluetoothGatt(14514): connect() - device: C0:20:12:14:10:01, auto: false
D/BluetoothGatt(14514): registerApp()
D/BluetoothGatt(14514): registerApp() - UUID=098334a0-d1d4-4875-91a8-0a2fdc242ba8
D/BluetoothGatt(14514): onClientRegistered() - status=0 clientIf=31
I/flutter (14514): [FBP] <connect> result: true
D/BluetoothGatt(14514): onClientConnectionState() - status=0 clientIf=31 device=C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onConnectionStateChange:connected
D/[FBP-Android](14514): [FBP]   status: SUCCESS
I/flutter (14514): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:20:12:14:10:01, connection_state: 1}
I/flutter (14514): [FBP] <readRssi> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: readRssi
D/BluetoothGatt(14514): readRssi() - device: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onReadRemoteRssi:
D/[FBP-Android](14514): [FBP]   rssi: -56
D/[FBP-Android](14514): [FBP]   status: GATT_SUCCESS (0)
I/flutter (14514): [FBP] <readRssi> result: true
I/flutter (14514): [FBP] [[ OnReadRssi ]] result: {error_string: GATT_SUCCESS, rssi: -56, success: 1, remote_id: C0:20:12:14:10:01, error_code: 0}
I/flutter (14514): [FBP] <discoverServices> args: C0:20:12:14:10:01
D/[FBP-Android](14514): [FBP] onMethodCall: discoverServices
D/BluetoothGatt(14514): discoverServices() - device: C0:20:12:14:10:01
I/flutter (14514): [FBP] <discoverServices> result: true
```

**Comment by chipweinberger** [comment]
seems like a bug in android, or your peripheral's firmware.

If you call `discoverServices`, but the `OnDiscoveredServices` callback is never called, then there is nothing FBP can do about it.

**Comment by chipweinberger** [comment]
if you find out the underlying cause, please report back. I'm curious. 

For now, I'll close because this is working as expected.

**Comment by hezhipengzipp** [comment]
??? I  met this quesion too

**Comment by ppupha** [comment]
I’m also getting this error: `discoverService` was called, but the `OnDiscoveredServices` callback is never triggered. However, I can still connect to the device and discover services using the `nRF Connect ` app.

**Comment by ekuleshov** [comment]
> I’m also getting this error: `discoverService` was called, but the `OnDiscoveredServices` callback is never triggered. However, I can still connect to the device and discover services using the `nRF Connect ` app.

@ppupha try to connect to your service from FBP example app

**Comment by ppupha** [comment]
> I’m also getting this error: discoverService was called, but the OnDiscoveredServices callback is never triggered. However, I can still connect to the device and discover services using the nRF Connect  app.
>
>@ppupha try to connect to your service from FBP example app

Tried with FBP example app. The device connects successfully but fails to discover services.
Here is the log:

```
I/flutter (26851): [FBP] <connect> args: {remote_id: C0:BF:BE:89:12:B7, auto_connect: 0}
D/[FBP-Android](26851): [FBP] onMethodCall: connect
D/CompatChangeReporter(26851): Compat change id reported: 265103382; UID 10397; state: ENABLED
D/BluetoothGatt(26851): connect() - device: XX:XX:XX:XX:12:B7, auto: false
D/BluetoothGatt(26851): registerApp()
D/BluetoothGatt(26851): registerApp() - UUID=73858745-5cbf-4b07-8d90-549e6ec5119d
D/BluetoothGatt(26851): onClientRegistered() - status=0 clientIf=50
W/WindowOnBackDispatcher(26851): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(26851): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/flutter (26851): [FBP] (connect) result: true
D/BluetoothGatt(26851): onClientConnectionState() - status=0 clientIf=50 connected=true device=C0:BF:BE:89:12:B7
D/[FBP-Android](26851): [FBP] onConnectionStateChange:connected
D/[FBP-Android](26851): [FBP]   status: SUCCESS
I/flutter (26851): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 0, disconnect_reason_string: SUCCESS, remote_id: C0:BF:BE:89:12:B7, connection_state: 1}
I/flutter (26851): [FBP] <readRssi> args: C0:BF:BE:89:12:B7
D/[FBP-Android](26851): [FBP] onMethodCall: readRssi
D/BluetoothGatt(26851): readRssi() - device: XX:XX:XX:XX:12:B7
D/[FBP-Android](26851): [FBP] onReadRemoteRssi:
D/[FBP-Android](26851): [FBP]   rssi: -43
D/[FBP-Android](26851): [FBP]   status: GATT_SUCCESS (0)
I/flutter (26851): [FBP] (readRssi) result: true
I/flutter (26851): [FBP] [[ OnReadRssi ]] result: {error_string: GATT_SUCCESS, rssi: -43, success: 1, remote_id: C0:BF:BE:89:12:B7, error_code: 0}
D/BluetoothGatt(26851): onConnectionUpdated() - Device=C0:BF:BE:89:12:B7 interval=6 latency=0 timeout=500 status=0
I/flutter (26851): [FBP] <discoverServices> args: C0:BF:BE:89:12:B7
D/[FBP-Android](26851): [FBP] onMethodCall: discoverServices
D/BluetoothGatt(26851): discoverServices() - device: XX:XX:XX:XX:12:B7
I/flutter (26851): [FBP] (discoverServices) result: true
I/flutter (26851): FlutterBluePlusException | discoverServices | fbp-code: 1 | Timed out after 15s
I/flutter (26851): backtrace: #0      FutureTimeout.fbpTimeout.<anonymous closure> (package:flutter_blue_plus/src/utils.dart:18:7)
I/flutter (26851): #1      _RootZone.run (dart:async/zone.dart:1670:54)
I/flutter (26851): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:998:34)
I/flutter (26851): <asynchronous suspension>
I/flutter (26851): #3      BluetoothDevice.discoverServices (package:flutter_blue_plus/src/bluetooth_device.dart:281:43)
I/flutter (26851): <asynchronous suspension>
I/flutter (26851): #4      _DeviceScreenState.onDiscoverServicesPressed (package:flutter_blue_plus_example/screens/device_screen.dart:130:19)
I/flutter (26851): <asynchronous suspension>
D/BluetoothGatt(26851): onClientConnectionState() - status=22 clientIf=50 connected=false device=C0:BF:BE:89:12:B7
D/[FBP-Android](26851): [FBP] onConnectionStateChange:disconnected
D/[FBP-Android](26851): [FBP]   status: CONNECTION_TERMINATED_BY_LOCAL_HOST
D/BluetoothGatt(26851): close()
D/BluetoothGatt(26851): unregisterApp() - mClientIf=50
I/flutter (26851): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 22, disconnect_reason_string: CONNECTION_TERMINATED_BY_LOCAL_HOST, remote_id: C0:BF:BE:89:12:B7, connection_state: 0}
```

**Comment by dev-dylan** [comment]
how to resolve this problem？i got it too.
